/**
 * Collects every error code the API can return and writes it into the frontend
 * as a union type.
 *
 * ── Why generated rather than kept in step by hand ─────────────────────────
 *
 * The frontend has to have a Vietnamese sentence for every code, and the only
 * way to be sure of that is for the compiler to check it. That needs the exact
 * set of codes as a TYPE on the frontend side — and a hand-copied list of 140
 * strings is a list that will be wrong within a month.
 *
 * Run by `npm run codes:generate`, and checked by CI: the drift check
 * regenerates and fails if the committed file differs, so the two sides cannot
 * part company through somebody forgetting to run this.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, "..", "src");
const OUT = join(HERE, "..", "..", "frontend", "src", "lib", "error-codes.generated.ts");

const ERROR_CLASSES = [
  "NotFoundError",
  "ValidationError",
  "ConflictError",
  "UnauthorizedError",
  "ForbiddenError",
  "MalformedBodyError",
  "PayloadTooLargeError",
  "UnsupportedMediaTypeError",
  "NotConfiguredError",
  "UpstreamUnavailableError",
].join("|");

/** `new SomeError("CODE", ...)` — the code is always the first argument. */
const THROWN = new RegExp(`new (?:${ERROR_CLASSES})\\(\\s*"([A-Z][A-Z0-9_]*)"`, "g");

/**
 * `code: "CODE"` inside the RESOURCE table in lib/parse-id.ts.
 *
 * Those never appear as a literal at a throw site — they are looked up — so a
 * scan for constructor calls alone would miss all ten and the frontend would be
 * required to have phrases for codes it can never see, while missing the ones
 * it will.
 */
const TABLE = /code:\s*"([A-Z][A-Z0-9_]*)"/g;

/** Raised by the error handler itself for anything that was not an AppError. */
const ALWAYS = ["INTERNAL_SERVER_ERROR"];

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === "generated" || entry === "node_modules") continue;
      yield* walk(full);
    } else if (entry.endsWith(".ts")) {
      yield full;
    }
  }
}

const codes = new Set<string>(ALWAYS);
for (const file of walk(SRC)) {
  const source = readFileSync(file, "utf8");
  for (const match of source.matchAll(THROWN)) codes.add(match[1]!);
  for (const match of source.matchAll(TABLE)) codes.add(match[1]!);
}

const sorted = [...codes].sort();
const body = `// GENERATED by backend/scripts/generate-error-codes.ts — do not edit.
//
// Every error code the API can return. Regenerate with:
//   cd backend && npm run codes:generate
//
// The dictionary in lib/error-messages.ts is typed against this union, so a
// code added here without a Vietnamese phrase fails to compile.

export type BackendErrorCode =
${sorted.map((code) => `  | '${code}'`).join("\n")}

export const BACKEND_ERROR_CODES = ${sorted.length} as const
`;

/*
 * `--check` compares rather than writes.
 *
 * It compares CONTENT, not git state. The first version shelled out to
 * `git diff --exit-code`, which passes silently while the generated file is
 * untracked — so the guard was dormant exactly when it was newest, and the test
 * for it passed for the wrong reason.
 */
if (process.argv.includes("--check")) {
  let current: string | null = null;
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    current = null;
  }

  if (current !== body) {
    console.error(
      current === null
        ? `${OUT} is missing. Run: npm run codes:generate`
        : `${OUT} is out of date — the API's error codes have changed.\n` +
          `Run: npm run codes:generate`,
    );
    process.exit(1);
  }

  console.log(`${sorted.length} mã, khớp với ${OUT}`);
} else {
  writeFileSync(OUT, body);
  console.log(`${sorted.length} mã → ${OUT}`);
}
