/**
 * Naming the charges on a bill.
 *
 * Lives in `lib/` rather than in the invoices feature because BOTH surfaces
 * need it — the owner's screens and the tenant portal — and the portal is not
 * an owner feature. Duplicating it instead is what this placement exists to
 * prevent: a tenant querying a bill against the owner's screen is exactly when
 * two descriptions of one charge would surface, and it would surface as an
 * argument about whether the bill is right.
 */

/**
 * What a charge on a bill says, in the reader's language.
 *
 * ── Why the screen writes this rather than the backend ─────────────────────
 *
 * The stored `description` is written when the invoice is issued and frozen
 * there deliberately: it records what was charged. Translating the generator
 * would leave every existing invoice in English while new ones came out
 * Vietnamese, and rewriting the old ones would edit a historical record to make
 * it read better. So nothing stored changes and the screen renders instead.
 *
 * ── The split, which is the whole design ───────────────────────────────────
 *
 * Rent, electricity and water are GENERATED text: their stored description is a
 * rendering of fields that are also on the row. Rebuilding from those fields
 * loses nothing, and cannot drift from the figures because it reads them.
 *
 * A service fee and an ad-hoc charge are what a PERSON wrote — the owner's own
 * name for a fee in their catalogue, or their sentence about a broken window.
 * Those are shown exactly as written. Rewording them would be rewriting
 * somebody's words, most likely into the language they already used.
 *
 * This is not "translate what we can". It is that generated text is
 * reproducible and human text is not ours to touch.
 */
const DEPOSIT_PHRASES: { match: (d: string) => boolean; label: (d: string) => string }[] = [
  {
    // `Deposit, 2 month(s) of rent`
    match: (d) => /^Deposit, \d+ month\(s\) of rent$/.test(d),
    label: (d) => `Tiền cọc, ${d.match(/\d+/)![0]} tháng tiền thuê`,
  },
  { match: (d) => d === 'Deposit top-up on renewal', label: () => 'Bù thêm tiền cọc khi gia hạn' },
  { match: (d) => d === 'Deposit returned on renewal', label: () => 'Hoàn lại tiền cọc khi gia hạn' },
]

/**
 * Generated text that does NOT sit on a line whose kind implies it.
 *
 * Cancelling a tenancy records what the owner keeps as an ad-hoc `charge`,
 * because that is the machinery it reuses to reach the revenue report. So this
 * one phrase is written by the system while carrying the kind that otherwise
 * means "a person wrote this".
 *
 * Found by opening a cancelled tenancy's bill and seeing it in English — the
 * split by `kind` is a proxy for "who wrote it", and this is the line where the
 * proxy is wrong. Matched here rather than by widening the rule: exactly, and
 * only against this phrase, so an owner's own sentence about a broken window is
 * still untouched.
 */
const GENERATED_CHARGES: Record<string, string> = {
  'Deposit kept on cancellation': 'Tiền cọc giữ lại khi huỷ hợp đồng',
}

/**
 * What a line says, in Vietnamese where the system wrote it and verbatim where
 * a person did.
 *
 * ── Why deposit lines are matched by phrase ────────────────────────────────
 *
 * A deposit line's meaning is NOT determined by its kind. The four phrases mean
 * genuinely different things — money taken, topped up, handed back, kept — and
 * one of them carries a negative amount. Labelling all four "Tiền cọc" would
 * put a negative figure under a word that gives no account of why money is
 * going the other way.
 *
 * The alternative was re-deriving which is which from signals (a negative means
 * a return, an ad-hoc invoice means a cancellation). That is a second copy of a
 * rule the backend owns, in a place that cannot be kept in step with it — the
 * exact failure this codebase has spent several changes removing.
 *
 * Phrase matching is fragile in the ordinary sense: reword one in the backend
 * and it stops matching. But the set is closed and generated by code in this
 * repository, and the failure is GRACEFUL — an unmatched line falls through to
 * its stored text, which is today's behaviour. A wrong label is impossible;
 * only a missed one, and a missed one is visible to anyone who opens the bill.
 *
 * Matched in full and only on `deposit` lines. A prefix match would eventually
 * catch an owner-written charge beginning with the same word: a `charge` line
 * reading "Deposit returned to Mr Nam by hand" is the owner's sentence and
 * stays untouched.
 */
export function lineLabel(line: {
  kind: string
  description: string
  quantity: number | null
  periodStart: string | null
}): string {
  switch (line.kind) {
    case 'rent': {
      // The month the rent covers, taken from the period rather than parsed out
      // of the stored text.
      if (line.periodStart === null) return 'Tiền nhà'
      const d = new Date(line.periodStart)
      return `Tiền nhà tháng ${d.getUTCMonth() + 1}/${d.getUTCFullYear()}`
    }
    case 'electricity':
      return line.quantity === null ? 'Tiền điện' : `Tiền điện ${line.quantity} kWh`
    case 'water':
      return line.quantity === null ? 'Tiền nước' : `Tiền nước, ${line.quantity} người`
    case 'deposit': {
      const matched = DEPOSIT_PHRASES.find((p) => p.match(line.description))
      return matched ? matched.label(line.description) : line.description
    }
    case 'charge':
      // Almost always the owner's own sentence. The one exception is generated
      // — see GENERATED_CHARGES above.
      return GENERATED_CHARGES[line.description] ?? line.description
    // `serviceFee` falls through: it carries the owner's own catalogue name.
    default:
      return line.description
  }
}
